name: Check Generated Files

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: zola-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Check Zola
        run: zola check
      - name: Create CSS output
        run: tailwindcss -i themes/project-portfolio/src/css/main.css -o themes/project-portfolio/static/css/main.css --minify
      - name: Check for changed files
        run: |
          cd themes/project-portfolio
          if [ ! -z "$(git status --untracked-files=no --porcelain)" ]; then
            echo "::warning::$(git status --untracked-files=no --porcelain)"
            echo "::error title=Changed files::There are changed files in the repository after build"
            exit 1
          fi
